[deps]
Acquisition = "d4bbf60b-102b-5ffb-8f97-a7ea5817e69f"
BladeRFHardwareDriver_jll = "ddcda2f0-0770-5eff-b02e-03a583a735ee"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GNSSReceiver = "c84cffac-6943-4fe6-9449-f6d23817af8b"
GNSSSignals = "52c80523-2a4e-5c38-8979-05588f836870"
LibSigGUI = "d3b3b3cd-8983-4dfd-9422-9173a4c25e26"
LibSigflow = "21776f6c-6667-6973-6269-6c2d78727478"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PlotlyLight = "ca7969ec-10b3-423e-8d99-40f33abb42bf"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PositionVelocityTime = "52ec0b5e-ee36-11ea-211c-3d844fc5682d"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SoapyBladeRF_jll = "80aee790-0d4a-5951-bcd6-30e0bbfe317a"
SoapyLMS7_jll = "e7ed14a0-13eb-5dc7-93e2-6133b2eb8bed"
SoapyLoopback_jll = "8d250ce8-a086-56bd-8a36-e4e8f4202680"
SoapySDR = "4fa426e6-03fd-45b2-b2dd-25f726820c03"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Tracking = "10b2438b-ffd4-5096-aa58-44041d5c8f3b"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"
XTRX = "3933273f-6cdb-4250-9272-8aed09f39780"
soapysdr_jll = "343a40d9-ed99-5d34-8b56-649aaa4ecee6"
