[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
SoapySDR = "4fa426e6-03fd-45b2-b2dd-25f726820c03"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
