name = "JuliaForEngineers"
uuid = "adc118e1-5f12-4fe2-9c7a-fd85afaabfa8"
authors = [" <>"]
version = "0.1.0"

[deps]
BlockComponents = "1ef5d832-be8e-447f-9f2c-8b5d17d15fd3"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DyadEcosystemDependencies = "7bc808db-8006-421e-b546-062440d520b7"
DyadInterface = "99806f68-afab-45ca-9d8c-ceff6bc61f54"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
OrdinaryDiffEqDefault = "50262376-6c5a-4cf5-baba-aaf4f84d72d7"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
TranslationalComponents = "42acc370-819b-4877-bdd6-eb3294461f5d"

[compat]
BlockComponents = "2.4.5"
DifferentialEquations = "7.16.1"
DyadEcosystemDependencies = "=0.9.4"
ForwardDiff = "0.10.38"
Markdown = "1"
ModelingToolkit = "9.80.5"
NonlinearSolve = "4.9.0"
OrdinaryDiffEq = "6.101.0"
TranslationalComponents = "0.7.1"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "DataFrames", "Plots", "Test"]
